- id: turn_on_light_plants
  alias: turn_on_light_plants
  trigger:
  - platform: time
    at: 07:00
  condition: []
  action:
  - service: script.light_plants_on
  mode: single
- id: turn_off_light_plants
  alias: turn_off_light_plants
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - service: script.light_plants_off
  mode: single
- id: turn_on_autowatering
  alias: turn_on_autowatering
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.autowatering
  trigger:
    platform: time_pattern
    hours: /1
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.input_datetime.last_autowatering.state))
      /3600 > (states.input_number.autowatering_interval.state | int)}}'
- id: turn_on_autowatering_trigger
  alias: turn_on_autowatering_trigger
  trigger:
    platform: mqtt
    topic: home/kitchen/switch2/waterpump
  action:
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.last_autowatering
      time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
      date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'
- id: turn_on_warm_flow_morning
  alias: turn_on_warm_flow_morning
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.hall_warmfloor
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.turn_on_warm_flow_morning.state[0:5]
      }}'
  condition:
  - condition: state
    entity_id: group.all_person
    state: home
- id: turn_off_warm_flow_day
  alias: turn_off_warm_flow_day
  trigger:
  - entity_id: person.alesha
    event: leave
    platform: zone
    zone: zone.reutov
  - entity_id: person.polina
    event: leave
    platform: zone
    zone: zone.reutov
  condition:
  - after: '9:00'
    before: '22:00'
    condition: time
  action:
  - entity_id: switch.hall_warmfloor
    service: switch.turn_off
- id: turn_on_warm_flow_evening
  alias: turn_on_warm_flow_evening
  trigger:
  - entity_id: person.lesha
    event: enter
    platform: zone
    zone: zone.reutov
  - entity_id: person.polina
    event: enter
    platform: zone
    zone: zone.reutov
  condition:
  - after: '9:00'
    before: '22:00'
    condition: time
  action:
  - data: {}
    entity_id: switch.hall_warmfloor
    service: switch.turn_on
- id: turn_off_warm_flow_night
  alias: turn_off_warm_flow_night
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.hall_warmfloor
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.input_datetime.turn_off_warm_flow_night.state[0:5]
      }}'
- id: vacuum_cleaning
  alias: vacuum_cleaning
  description: Пылесосить. Проверяет была ли уборка сегодня
  trigger:
  - hours: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: group.all_person
    state: not_home
  - condition: template
    value_template: '{{states.vacuum.xiaomi_vacuum.attributes.clean_start.date() <
      now().date()}}'
  - after: 09:00
    before: '19:00'
    condition: time
  action:
  - entity_id: vacuum.rockrobo
    service: script.vacuum_all_zones
- id: test1
  alias: Webhook test
  description: Тестовая автоматизация
  trigger:
  - platform: webhook
    webhook_id: test
  action:
  - data_template:
      message: '{{ trigger.data.a }}

        '
      name: testlog
    service: logbook.log
- id: mqtt_started
  alias: mqtt_start
  trigger:
  - platform: mqtt
    topic: Start
  action:
  - data_template:
      message: '{{ trigger.payload }}

        '
      name: started
    service: logbook.log
- id: '1581284354574'
  alias: Test
  description: Test
  trigger:
  - hours: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: group.all_person
    state: not_home
  action:
  - delay: '1'
- id: bathroom_fan
  alias: Вытяжка в ванной
  description: Включать автоматическую вентиляцию
  trigger:
  - platform: mqtt
    topic: home/bathroom/dht
  condition:
  - condition: template
    value_template: '{{states.sensor.bathroom_humidity.state | int >= states.sensor.humidity.state
      | int + 20}}'
  - condition: state
    entity_id: fan.bathroom_fan
    state: 'off'
  - condition: state
    entity_id: timer.bathroom_dht_healthcheck
    state: active
  - condition: state
    entity_id: timer.hall_dht_healthcheck
    state: active
  - condition: not
    conditions:
    - condition: state
      entity_id: timer.stop_fan
      state: active
  action:
  - data:
      payload: '{"action":"hold","duration": 370000}'
      topic: home/bathroom/switch/fan
    service: mqtt.publish
  mode: single
- id: '1593975121400'
  alias: bathroom_fan_trigger
  description: Блокировать вытяжку в ванной
  trigger:
  - payload: '0'
    platform: mqtt
    topic: home/bathroom/switch/fan/state/manual
  condition: []
  action:
  - data:
      duration: 00:10:00
    entity_id: timer.stop_fan
    service: timer.start
- id: '1604089961695'
  alias: bathroom_dht_healthcheck
  description: ''
  trigger:
  - platform: mqtt
    topic: home/bathroom/dht
  condition: []
  action:
  - service: timer.start
    data: {}
    entity_id: timer.bathroom_dht_healthcheck
  mode: single
- id: '1604090171999'
  alias: hall_dht_healthcheck
  description: ''
  trigger:
  - platform: mqtt
    topic: home/hall/dht
  condition: []
  action:
  - service: timer.start
    data: {}
    entity_id: timer.hall_dht_healthcheck
  mode: single
- id: '1606046099343'
  alias: Яндекс влажность в доме
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Какая влажность в доме?
  condition: []
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.yandex_station
      media_content_id: Влажность в доме {{ states("sensor.humidity")|round|format(morph='процент',
        as_text=false) }}
      media_content_type: text
  mode: single
- id: '1606387908769'
  alias: Яндекс температура в доме
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Какая температура в доме?
  condition: []
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.yandex_station
      media_content_id: Температура в доме {{ states("sensor.temperature")|round|format(morph='градус',
        as_text=false) }}
      media_content_type: text
  mode: single
- id: '1654717812218'
  alias: Яндекс станция. Увеличить громкость утром
  description: ''
  trigger:
  - platform: time_pattern
    hours: '7'
    minutes: '00'
    seconds: '00'
  condition: []
  action:
  - repeat:
      for_each:
      - media_player.yandex_station_white
      - media_player.yandex_station
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: '{{repeat.item}}'
        data:
          volume_level: 0.5
  mode: single
- id: '1654719566999'
  alias: Яндекс станция. Уменьшить громкость вечером
  description: ''
  trigger:
  - platform: time_pattern
    hours: '20'
    minutes: '00'
    seconds: '00'
  condition: []
  action:
  - repeat:
      for_each:
      - media_player.yandex_station_white
      - media_player.yandex_station
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: '{{repeat.item}}'
        data:
          volume_level: 0.4
  mode: single
- id: '1655580244891'
  alias: Яндекс станция черная. Увеличить громкость Алисы
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.yandex_station
    attribute: alice_state
    to: SPEAKING
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.yandex_station_volume
    data:
      value: '{{states.media_player.yandex_station.attributes.volume_level}}'
  - service: media_player.volume_set
    entity_id: media_player.yandex_station
    data:
      volume_level: '{{states.media_player.yandex_station.attributes.volume_level
        + 0.1}}'
  mode: single
- id: '1655580313362'
  alias: Яндекс станция черная. Уменьшить громкость Алисы
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.yandex_station
    attribute: alice_state
    from: SPEAKING
  condition: []
  action:
  - service: media_player.volume_set
    entity_id: media_player.yandex_station
    data:
      volume_level: '{{states.input_number.yandex_station_volume.state}}'
  mode: single
- id: '1663965751919'
  alias: Яндекс станция белая. Нормализация громкости
  description: Автоматически уменьшает громкость музыки
  trigger:
  - platform: template
    value_template: '{{states.media_player.yandex_station_white.attributes.alice_state
      == "IDLE" and states.media_player.yandex_station_white.state == "playing" }}'
    id: turn_down
  - id: turn_up
    platform: state
    entity_id:
    - media_player.yandex_station_white
    attribute: alice_state
    to: SPEAKING
  - platform: state
    entity_id:
    - media_player.yandex_station_white
    attribute: volume_level
    id: on_volume_changed
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - alias: Событие turn_down
        condition: trigger
        id: turn_down
      - alias: Громкость уже установлена
        condition: template
        value_template: "{{states.media_player.yandex_station_white.attributes.volume_level
          | float\n  != (states.input_number.yandex_station_white_volume.state | float
          - 0.1) | round(1)}}     "
        enabled: false
    - and:
      - or:
        - and:
          - alias: Событие turn_up
            condition: trigger
            id: turn_up
          - alias: Громкость уже установлена
            condition: template
            value_template: "{{states.media_player.yandex_station_white.attributes.volume_level
              | float\n  != states.input_number.yandex_station_white_volume.state
              | float}}"
        - and:
          - alias: Событие on_volume_changed
            condition: trigger
            id: on_volume_changed
          - not:
            - condition: state
              entity_id: timer.yandex_station_volume_lock
              state: active
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: turn_down
      sequence:
      - service: timer.start
        target:
          entity_id: timer.yandex_station_volume_lock
        data: {}
      - service: media_player.volume_set
        entity_id: media_player.yandex_station_white
        data:
          volume_level: '{{(states.input_number.yandex_station_white_volume.state
            | float - 0.1) | round(1)}}        '
    - conditions:
      - condition: trigger
        id: turn_up
      sequence:
      - service: timer.start
        target:
          entity_id: timer.yandex_station_volume_lock
        enabled: true
      - service: media_player.volume_set
        entity_id: media_player.yandex_station_white
        data:
          volume_level: '{{states.input_number.yandex_station_white_volume.state}}'
    - conditions:
      - condition: trigger
        id: on_volume_changed
      sequence:
      - if:
        - alias: изменили громкость музыки из приложения
          condition: template
          value_template: "{{ states.media_player.yandex_station_white.state == \"playing\"\n
            \ }}        "
        then:
        - alias: Прибавим 0.1
          service: input_number.set_value
          target:
            entity_id: input_number.yandex_station_white_volume
          data:
            value: '{{states.media_player.yandex_station_white.attributes.volume_level
              | float + 0.1 | round(1)}}'
        else:
        - service: input_number.set_value
          target:
            entity_id: input_number.yandex_station_white_volume
          data:
            value: '{{states.media_player.yandex_station_white.attributes.volume_level}}'
  mode: queued
  max: 2
- id: '1667499588499'
  alias: Проходной выключатель. Коридор
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 55cd6b6ef2820223c79aae4bbb4feb4f
    entity_id: switch.kitchen_light_switch_2
    domain: switch
    id: turn_on
  - platform: device
    type: turned_off
    device_id: 55cd6b6ef2820223c79aae4bbb4feb4f
    entity_id: switch.kitchen_light_switch_2
    domain: switch
    id: turn_off
  - platform: mqtt
    topic: home/hall/switch/lamp/state
    payload: '1'
    id: is_on
  - platform: mqtt
    topic: home/hall/switch/lamp/state
    payload: '0'
    id: is_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: turn_on
      sequence:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.hall_lamp
    - conditions:
      - condition: trigger
        id: turn_off
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.hall_lamp
    - conditions:
      - condition: trigger
        id: is_on
      sequence:
      - type: turn_on
        device_id: 55cd6b6ef2820223c79aae4bbb4feb4f
        entity_id: switch.kitchen_light_switch_2
        domain: switch
    - conditions:
      - condition: trigger
        id: is_off
      sequence:
      - type: turn_off
        device_id: 55cd6b6ef2820223c79aae4bbb4feb4f
        entity_id: switch.kitchen_light_switch_2
        domain: switch
  mode: single
